# Generated by Django 4.0 on 2024-06-23 17:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('game_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaccountdetails',
            name='telegram_link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('trans_type', models.CharField(choices=[('withdrawal', 'WITHDRAWAL'), ('deposit', 'DEPOSIT')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('successful', 'SUCCESSFUL'), ('failed', 'FAILED')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
    ]
