# Generated by Django 4.0 on 2024-06-25 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('game_provider', '0003_withdrawalrequest_depositrequest_bet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='auth.user'),
        ),
    ]
