# Generated by Django 4.0 on 2024-06-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='phone_number',
            field=models.CharField(default='+1-0000000000', max_length=20),
        ),
    ]
