# Generated by Django 4.0 on 2024-06-23 17:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0003_alter_userdetails_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='userdetails',
            name='profile_img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authenticator.profileimage'),
        ),
    ]
